### ISSUE TITLE
Add workflow for updating driver data 

### ISSUE THREAD

**Issue by jzwart** [USGS-R/delaware-model-prep#24]
Hayley pulled driver data from 2017-2019 using Rich McDonald's workflow. We should incorporate this workflow into this pipeline so that we can continue to update driver data and SNTemp runs.

**Comment by aappling-usgs** [comment]
Changing name:
1. to make it clearer this is a pipeline task, not just an external data updating task, and
2. because I'm wondering if getting the uncal SNTemp predictions should actually be a part of #42 instead of this task (or maybe it should be both places - here we _pull_ uncal SNTemp from Yeti, in #42 we _generate_ such predictions ourselves?).

**Comment by jzwart** [comment]
Yeah, good point @aappling-usgs , this should probably just be `Add workflow for updating driver data`, which I think is a big enough and separate task to have it's own issue. 
To me, the pulling of PRMS-SNTemp model seems best in #42 rather than here as the pulling of PRMS-SNTemp should be a 1-time task and it isn't necessary to repull the model when updating the driver data.
