### ISSUE TITLE
Add flow sites to crosswalk

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#3]
Some flow sites might be dropped if there isn't also temperature data. This is because the crosswalk is currently based on temperature sites. Could just make a call to `whatNWISsites` for flow upstream, and make sure those get in the crosswalk. This would be a precursor for pulling flow data from NWIS, which should be done anyway.

**Comment by jsadler2** [comment]
I am thinking about this now since I want to make a plot of the flow sites, the temp sites, and the flow and temp sites. I can write code to pull flow data from NWIS, but I'm not sure how to include the sites in the cross-walk. One thing that would be helpful for me would be to add a column in that table to indicate whether the site has temp, flow, or both.

**Comment by jsadler2** [comment]
>This would be a precursor for pulling flow data from NWIS, which should be done anyway.

I can do this in Python w/o much trouble, but if you already have it set up to get temp, could we just use basically the same R functions and just swap out USGS parameter codes?

>Could just make a call to whatNWISsites for flow upstream

also, is `whatNWISsites` called for getting the temp data? I can't see it in the code. I am R/scipiper illiterate.

**Comment by limnoliver** [comment]
I don't think it's you -- the pulling of temp data happens in a [different pipeline](https://github.com/USGS-R/2wp-temp-observations). I use `whatNWISdata` in this case, and I would do the same for flow if I were doing an actual data pull (versus just adding sites metadata, which I was suggesting above). This is  [where I use whatNWISdata](https://github.com/USGS-R/2wp-temp-observations/blob/master/2_nwis_pull/src/inventory_nwis.R#L12-L18). 

We could add flow to that pipeline in order start getting national data. Thoughts? Alternatively, I'm guessing WBEEP has a national flow dataset that corresponds to their points of interest that were used to create the geofabric.

**Comment by jread-usgs** [comment]
If getting flow nationally, might want to ping Lindsay, who was asking about a historical discharge data rebuild yesterday. At a minimum, would be good to know both effort are happening. On top of that, might be able to share some code or hints for efficient solutions w/ the services.

**Comment by limnoliver** [comment]
After discussing with Lindsay - there are broader needs (outside of this group) for national discharge data. A repo that is project agnostic (e.g., "national-discharge") might be the best path forward, then others can tie to their project pipelines however they see fit. One identified lesson learned from temperature that might be useful for gages-through-ages is that some sites that are in UV are not in DV, so should use the same [pattern ](https://github.com/USGS-R/2wp-temp-observations/blob/master/2_nwis_pull.yml#L61-L78) of taking an inventory of both, and pulling only UV sites that are not in DV.

**Comment by jsadler2** [comment]
> A repo that is project agnostic (e.g., "national-discharge") might be the best path forward, then others can tie to their project pipelines however they see fit.

That sounds fine to me. Although I imagine most folks would rather just have the data if available rather than the code to gather the data - especially if at a national scale which would take hours to pull. But since the data is needed in many projects, and the code has to live somewhere, it would make sense to have it in its own repo.
>  pulling only UV sites that are not in DV

Do you then aggregate the `UV` to a daily time scale by taking the daily average?

**Comment by jsadler2** [comment]
cc @lindsayplatt

**Comment by limnoliver** [comment]
Yes, there would be a shared cache for the data so that people _don't_ need to repull data, only if they want to update the data. 

Yes, with the temperature data, I reduce UV down to average daily values.

**Comment by lindsayplatt** [comment]
For the gages-through-the-ages viz, we are using these data pulls to get a count of active gages. The count of gages is ultimately what we need, so aggregating UV into daily averages is not necessary for our purposes. 

I am thinking that it would be cool if we were able to modify this repo to also pull gage height because we use that for the gage conditions animations. BUT that isn't as immediate of a need. Those would need UV to be summarized to daily averages. Maybe the repo could be `national-stream-data` or something so that we could add other params in the future. Or maybe those should be separate repos.

**Comment by jsadler2** [comment]
I like the idea of leaving the name general b/c much of the functionality should be the same for the different variable. `national-stream-data` sounds good to me.

I also have to say, I love the name, "gages-through-the-ages"

**Comment by jsadler2** [comment]
Coming back to the original post topic (I think): I just looked at our `obs_flow_full.csv` and our `obs_temp_full.csv`. In these files, there are no segments that have flow observations that do not also have temperature observations. Is that why you made this issue originally - to check for sites that have flow but not temperature?

**Comment by limnoliver** [comment]
Yes, thanks for circling back. Because I don't explicitly include the flow sites in the crosswalk, I thought I might be dropping flow sites further down the pipeline.

**Comment by limnoliver** [comment]
Flow data now pulled from NWIS in [national-flow-observations](https://github.com/USGS-R/national-flow-observations) pipeline. Next step is to incorporate flow into the pipeline similar to how the temperature data is pulled in and matched to network.
