### ISSUE TITLE
Issue running PRMS-SNTemp in pipeline

### ISSUE THREAD

**Issue by limnoliver** [USGS-R/delaware-model-prep#84]
Both Sam and Alison independently had a hard time building the PRMS-SNTemp portion of the pipeline. Alison got stuck on target `set_sntemp_output_vars`. In both cases, we had to force rebuild `3_predictions/tmp/control/delaware.control.ind`.

Not super high priority since we currently have a hack solution, but should resolve.

**Comment by aappling-usgs** [comment]
I think I found a clue:
![image](https://user-images.githubusercontent.com/12039957/110674350-cd5adf80-819f-11eb-8636-0c3fd8b3e8ec.png)

Looks like we've git versioned the build/status file for delaware.control.ind, but not delaware.control.ind itself. I'm not totally sure this explains why scipiper thought there was no need to build delaware.control.ind (because the file was completely missing before I force-built it!), but it might indeed be the explanation. If so, then the solution is probably to modify .gitignore to not include delaware.control.ind, and then git version that file.

**Comment by aappling-usgs** [comment]
Oh, wait - delaware.control.ind already _is_ in the repo! https://github.com/USGS-R/delaware-model-prep/blob/master/3_predictions/tmp/control/delaware.control.ind.

So maybe it's that delaware.control.ind is vouching for the local presence of delaware.control, when in fact on new clones/updates of the repo (e.g., mine just now) delaware.control is not available?

**Comment by aappling-usgs** [comment]
Thinking about this just a tiny bit more before I leave it for another day and/or Jake: maybe the solution is to NOT git commit either delaware.control.ind or the associated build/status file (i.e., remove them from the git repo) so that in order for that file to exist, you have to build it locally. That seems like it's probably more consistent with the way that file is being used. If that is the solution, then I'd also recommend changing the extension (e.g., to '.yml') to help communicate that it has the form of an indicator file but is intentionally being excluded because it's an indicator of the state of the local repo, not an indicator of the state of the shared cache.

**Comment by jzwart** [comment]
Alison, I think your solution is probably best. We need `delaware.control` locally if we need to rerun PRMS-SNTemp due to changes in model start or stop, or the variables output from PRMS-SNTemp.  

Or the fetching & running of the model could be put into one target of `3_predictions/tmp/output/stream_temp.out.nsegment.ind` which currently just runs the model and outputs. 

Another note, if we move everything to Caldera, then the fetching target will go away since the model will be available on Caldera already

**Comment by limnoliver** [comment]
prms is now run in https://code.usgs.gov/wma/wp/run-prms-sntemp
